version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgresDB
      POSTGRES_DB: HeliCareDB
    ports:
      - '5999:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
